#include "sde_trigger.h"
#include "sde_trigger_options.h"

 // Global definitions for the sde trigger
 // 
 // 14-Jan-14 DFN Initial version
 // 14-May-14 DFN Added SHWR_MEM_WIDTH
 // 06-Jun-14 DFN Start defining status register bits
 // 19-Jun-15 DFN Add trace start registers

#ifndef _TRIGGER_DEFS
 #define _TRIGGER_DEFS

 #define ADC_WIDTH 12 // Number of bits per ADC
 #define NUM_ADCS 10  // Number of ADCs

 #define WIDTH_BITS 9 // Number of bits in ToT occupancy register

 #define SHWR_MEM_WIDTH 32      // Width of each shower memory block
 #define SHWR_MEM_ADDR_WIDTH 32 // Vivado seems to require 32 bit bus
                                // even though only use a fraction of it.
 #define SHWR_MEM_BUF_SHIFT 13  // Shower memory buffer number shift
                                // Depth of each shower memory buffer (*4 since
                                // addressing is in bytes - 4 to a word)
 #define SHWR_MEM_DEPTH (1<<SHWR_MEM_BUF_SHIFT)
 #define SHWR_MEM_WORDS (SHWR_MEM_DEPTH/4)
 #define SHWR_MEM_NBUF 4        // Number of shower memory buffers
 #define SHWR_BUF_NUM_WIDTH 3   // Width of buffer number register (for ttag)
 #define SHWR_EVT_CTR_WIDTH 4   // Width of shower event counter (for ttag)
                                // Delay from trigger to end of buffer
 #define SHWR_TRIG_DLY ((SHWR_MEM_WORDS*2)/3)
                                // Dead length till next possible trigger,
                                // not counting logic delays
 #define SHWR_DEAD_DLY (SHWR_MEM_WORDS) // Not counting logic delays
 #define MUON_MEM_WIDTH 32      // Width of each muon memory
 #define MUON_MEM_ADDR_WIDTH 32 // Vivado seems to require 32 bit bus
                                // even though only use a fraction of it.
 #define MUON_MEM_BUF_SHIFT 16  // Muon memory buffer number shift
                                // Depth of each muon memory buffer
 #define MUON_MEM_DEPTH (1<<MUON_MEM_BUF_SHIFT)
 #define MUON_MEM_WORDS (MUON_MEM_DEPTH/4)
 #define MUON_MEM_NBUF 4        // Number of muon memory buffers
 #define MUON_BUF_NUM_WIDTH 3   // Width of buffer number register (for ttag)
 #define MUON_EVT_CTR_WIDTH 4   // Width of muon event counter (for ttag)

 #define SHWR_TRIGGER_INTR_BIT 0 // Shower trigger bit in interrupt regs.  
 #define MUON_TRIGGER_INTR_BIT 1 // Muon trigger bit in interrupt regs.  



// Define "Addresses" of trigger registers
// The first 128 registers are used in compatibility mode and are assigned, 
// as much as possible, to be the same as the pre-upgrade trigger registers.
// Not all of the addresses are used.

#define COMPATIBILITY_MUON_TRIG_THR0 SDE_TRIGGER_S00_AXI_SLV_REG016_OFFSET
#define COMPATIBILITY_MUON_TRIG_THR0_ADDR 016
#define COMPATIBILITY_MUON_TRIG_THR1 SDE_TRIGGER_S00_AXI_SLV_REG017_OFFSET
#define COMPATIBILITY_MUON_TRIG_THR1_ADDR 017
#define COMPATIBILITY_MUON_TRIG_THR2 SDE_TRIGGER_S00_AXI_SLV_REG018_OFFSET
#define COMPATIBILITY_MUON_TRIG_THR2_ADDR 018
#define COMPATIBILITY_MUON_TRIG_ENAB SDE_TRIGGER_S00_AXI_SLV_REG020_OFFSET
#define COMPATIBILITY_MUON_TRIG_ENAB_ADDR 020

#define COMPATIBILITY_AMIGA_TRIG SDE_TRIGGER_S00_AXI_SLV_REG021_OFFSET
#define COMPATIBILITY_AMIGA_TRIG_ADDR 021

#define COMPATIBILITY_MOPS_TRIG_MIN0 SDE_TRIGGER_S00_AXI_SLV_REG022_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MIN0_ADDR 022
#define COMPATIBILITY_MOPS_TRIG_MIN1 SDE_TRIGGER_S00_AXI_SLV_REG023_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MIN1_ADDR 023
#define COMPATIBILITY_MOPS_TRIG_MIN2 SDE_TRIGGER_S00_AXI_SLV_REG024_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MIN2_ADDR 024
#define COMPATIBILITY_MOPS_TRIG_MAX0 SDE_TRIGGER_S00_AXI_SLV_REG025_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MAX0_ADDR 025
#define COMPATIBILITY_MOPS_TRIG_MAX1 SDE_TRIGGER_S00_AXI_SLV_REG026_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MAX1_ADDR 026
#define COMPATIBILITY_MOPS_TRIG_MAX2 SDE_TRIGGER_S00_AXI_SLV_REG027_OFFSET
#define COMPATIBILITY_MOPS_TRIG_MAX2_ADDR 027
#define COMPATIBILITY_MOPS_TRIG_ENAB SDE_TRIGGER_S00_AXI_SLV_REG028_OFFSET
#define COMPATIBILITY_MOPS_TRIG_ENAB_ADDR 028
#define COMPATIBILITY_MOPS_TRIG_INT SDE_TRIGGER_S00_AXI_SLV_REG029_OFFSET
#define COMPATIBILITY_MOPS_TRIG_INT_ADDR 029
#define COMPATIBILITY_MOPS_TRIG_OCC SDE_TRIGGER_S00_AXI_SLV_REG030_OFFSET
#define COMPATIBILITY_MOPS_TRIG_OCC_ADDR 030
#define COMPATIBILITY_MOPS_TRIG_OFS SDE_TRIGGER_S00_AXI_SLV_REG031_OFFSET
#define COMPATIBILITY_MOPS_TRIG_OFS_ADDR 031

#define COMPATIBILITY_MUON_BUF_TIMER_A SDE_TRIGGER_S00_AXI_SLV_REG032_OFFSET
#define COMPATIBILITY_MUON_BUF_TIMER_A_ADDR 032
#define COMPATIBILITY_MUON_BUF_TIMER_B SDE_TRIGGER_S00_AXI_SLV_REG033_OFFSET
#define COMPATIBILITY_MUON_BUF_TIMER_B_ADDR 033
#define COMPATIBILITY_MUON_BUF_TIME_TAG_A SDE_TRIGGER_S00_AXI_SLV_REG034_OFFSET
#define COMPATIBILITY_MUON_BUF_TIME_TAG_A_ADDR 034
#define COMPATIBILITY_MUON_BUF_TIME_TAG_B SDE_TRIGGER_S00_AXI_SLV_REG035_OFFSET
#define COMPATIBILITY_MUON_BUF_TIME_TAG_B_ADDR 035
#define COMPATIBILITY_MUON_BUF_TRIG_MASK SDE_TRIGGER_S00_AXI_SLV_REG036_OFFSET
#define COMPATIBILITY_MUON_BUF_TRIG_MASK_ADDR 036
#define COMPATIBILITY_MUON_BUF_CONTROL SDE_TRIGGER_S00_AXI_SLV_REG037_OFFSET
#define COMPATIBILITY_MUON_BUF_CONTROL_ADDR 037
#define COMPATIBILITY_MUON_BUF_STATUS SDE_TRIGGER_S00_AXI_SLV_REG038_OFFSET
#define COMPATIBILITY_MUON_BUF_STATUS_ADDR 038
#define COMPATIBILITY_MUON_BUF_WORD_COUNT SDE_TRIGGER_S00_AXI_SLV_REG039_OFFSET
#define COMPATIBILITY_MUON_BUF_WORD_COUNT_ADDR 039

#define COMPATIBILITY_SHWR_BUF_TRIG_MASK SDE_TRIGGER_S00_AXI_SLV_REG040_OFFSET
#define COMPATIBILITY_SHWR_BUF_TRIG_MASK_ADDR 040
#define COMPATIBILITY_SHWR_BUF_TRIG_ID SDE_TRIGGER_S00_AXI_SLV_REG041_OFFSET
#define COMPATIBILITY_SHWR_BUF_TRIG_ID_ADDR 041
  #define COMPATIBILITY_SHWR_BUF_TRIG_SB 1
  #define COMPATIBILITY_SHWR_BUF_TRIG_TOT 2
  #define COMPATIBILITY_SHWR_BUF_TRIG_TOTD 4
  #define COMPATIBILITY_SHWR_BUF_TRIG_MOPS 8
  #define COMPATIBILITY_SHWR_BUF_TRIG_EXT 16
  #define COMPATIBILITY_SHWR_BUF_TRIG_RNDM 32
  #define COMPATIBILITY_SHWR_BUF_PRESCALE_TRG_SHFT 6
  #define COMPATIBILITY_SHWR_BUF_DLYD_TRG_SHFT 8
#define COMPATIBILITY_SHWR_BUF_STATUS SDE_TRIGGER_S00_AXI_SLV_REG043_OFFSET
#define COMPATIBILITY_SHWR_BUF_STATUS_ADDR 043

#define COMPATIBILITY_TRIG_RATES SDE_TRIGGER_S00_AXI_SLV_REG044_OFFSET
#define COMPATIBILITY_TRIG_RATES_ADDR 044
#define COMPATIBILITY_DELAYED_RATES SDE_TRIGGER_S00_AXI_SLV_REG045_OFFSET
#define COMPATIBILITY_DELAYED_RATES_ADDR 045

#define COMPATIBILITY_GLOBAL_CONTROL SDE_TRIGGER_S00_AXI_SLV_REG046_OFFSET
#define COMPATIBILITY_GLOBAL_CONTROL_ADDR 046
 #define COMPATIBILITY_GLOBAL_CONTROL_RESET_BIT 1

#define COMPATIBILITY_ID_A SDE_TRIGGER_S00_AXI_SLV_REG047_OFFSET
#define COMPATIBILITY_ID_A_ADDR 047

#define COMPATIBILITY_SB_TRIG_THR0 SDE_TRIGGER_S00_AXI_SLV_REG048_OFFSET
#define COMPATIBILITY_SB_TRIG_THR0_ADDR 048
#define COMPATIBILITY_SB_TRIG_THR1 SDE_TRIGGER_S00_AXI_SLV_REG049_OFFSET
#define COMPATIBILITY_SB_TRIG_THR1_ADDR 049
#define COMPATIBILITY_SB_TRIG_THR2 SDE_TRIGGER_S00_AXI_SLV_REG050_OFFSET
#define COMPATIBILITY_SB_TRIG_THR2_ADDR 050
#define COMPATIBILITY_SB_TRIG_ENAB SDE_TRIGGER_S00_AXI_SLV_REG052_OFFSET
#define COMPATIBILITY_SB_TRIG_ENAB_ADDR 052
 #define COMPATIBILITY_SB_TRIG_ENAB_SHIFT 3
 #define COMPATIBILITY_SB_TRIG_ENAB_WIDTH 3
 #define COMPATIBILITY_SB_TRIG_INCL_PMT0 (1<<COMPATIBILITY_SB_TRIG_ENAB_SHIFT)
 #define COMPATIBILITY_SB_TRIG_INCL_PMT1 (2<<COMPATIBILITY_SB_TRIG_ENAB_SHIFT)
 #define COMPATIBILITY_SB_TRIG_INCL_PMT2 (4<<COMPATIBILITY_SB_TRIG_ENAB_SHIFT)
 #define COMPATIBILITY_SB_TRIG_COINC_LVL_MASK 0x3
 #define COMPATIBILITY_SB_TRIG_COINC_LVL_SHIFT 6
 #define COMPATIBILITY_SB_TRIG_COINC_LVL_WIDTH 2
 #define COMPATIBILITY_SB_TRIG_REQ2BINS 0x200

#define COMPATIBILITY_RANDOM_TRIG_DELAY_A SDE_TRIGGER_S00_AXI_SLV_REG053_OFFSET
#define COMPATIBILITY_RANDOM_TRIG_DELAY_A_ADDR 053
#define COMPATIBILITY_RANDOM_TRIG_DELAY_B SDE_TRIGGER_S00_AXI_SLV_REG054_OFFSET
#define COMPATIBILITY_RANDOM_TRIG_DELAY_B_ADDR 054
#define COMPATIBILITY_RANDOM_TRIG_START SDE_TRIGGER_S00_AXI_SLV_REG055_OFFSET
#define COMPATIBILITY_RANDOM_TRIG_START_ADDR 055

#define COMPATIBILITY_TOT_TRIG_THR0 SDE_TRIGGER_S00_AXI_SLV_REG056_OFFSET
#define COMPATIBILITY_TOT_TRIG_THR0_ADDR 056
#define COMPATIBILITY_TOT_TRIG_THR1 SDE_TRIGGER_S00_AXI_SLV_REG057_OFFSET
#define COMPATIBILITY_TOT_TRIG_THR1_ADDR 057
#define COMPATIBILITY_TOT_TRIG_THR2 SDE_TRIGGER_S00_AXI_SLV_REG058_OFFSET
#define COMPATIBILITY_TOT_TRIG_THR2_ADDR 058
#define COMPATIBILITY_TOT_TRIG_ENAB SDE_TRIGGER_S00_AXI_SLV_REG060_OFFSET
#define COMPATIBILITY_TOT_TRIG_ENAB_ADDR 060
#define COMPATIBILITY_TOT_TRIG_OCC SDE_TRIGGER_S00_AXI_SLV_REG062_OFFSET
#define COMPATIBILITY_TOT_TRIG_OCC_ADDR 062

#define COMPATIBILITY_TOTD_TRIG_THR0 SDE_TRIGGER_S00_AXI_SLV_REG064_OFFSET
#define COMPATIBILITY_TOTD_TRIG_THR0_ADDR 064
#define COMPATIBILITY_TOTD_TRIG_THR1 SDE_TRIGGER_S00_AXI_SLV_REG065_OFFSET
#define COMPATIBILITY_TOTD_TRIG_THR1_ADDR 065
#define COMPATIBILITY_TOTD_TRIG_THR2 SDE_TRIGGER_S00_AXI_SLV_REG066_OFFSET
#define COMPATIBILITY_TOTD_TRIG_THR2_ADDR 066
#define COMPATIBILITY_TOTD_TRIG_UP0 SDE_TRIGGER_S00_AXI_SLV_REG067_OFFSET
#define COMPATIBILITY_TOTD_TRIG_UP0_ADDR 067
#define COMPATIBILITY_TOTD_TRIG_UP1 SDE_TRIGGER_S00_AXI_SLV_REG068_OFFSET
#define COMPATIBILITY_TOTD_TRIG_UP1_ADDR 068
#define COMPATIBILITY_TOTD_TRIG_UP2 SDE_TRIGGER_S00_AXI_SLV_REG069_OFFSET
#define COMPATIBILITY_TOTD_TRIG_UP2_ADDR 069
#define COMPATIBILITY_TOTD_TRIG_ENAB SDE_TRIGGER_S00_AXI_SLV_REG070_OFFSET
#define COMPATIBILITY_TOTD_TRIG_ENAB_ADDR 070
#define COMPATIBILITY_TOTD_TRIG_OCC SDE_TRIGGER_S00_AXI_SLV_REG072_OFFSET
#define COMPATIBILITY_TOTD_TRIG_OCC_ADDR 072
#define COMPATIBILITY_TOTD_TRIG_FD SDE_TRIGGER_S00_AXI_SLV_REG073_OFFSET
#define COMPATIBILITY_TOTD_TRIG_FD_ADDR 073
#define COMPATIBILITY_TOTD_TRIG_FN SDE_TRIGGER_S00_AXI_SLV_REG074_OFFSET
#define COMPATIBILITY_TOTD_TRIG_FN_ADDR 074

#define COMPATIBILITY_SCALAR_A_THR0 SDE_TRIGGER_S00_AXI_SLV_REG080_OFFSET
#define COMPATIBILITY_SCALAR_A_THR0_ADDR 080
#define COMPATIBILITY_SCALAR_A_THR1 SDE_TRIGGER_S00_AXI_SLV_REG081_OFFSET
#define COMPATIBILITY_SCALAR_A_THR1_ADDR 081
#define COMPATIBILITY_SCALAR_A_THR2 SDE_TRIGGER_S00_AXI_SLV_REG082_OFFSET
#define COMPATIBILITY_SCALAR_A_THR2_ADDR 082
#define COMPATIBILITY_SCALAR_A_ENAB SDE_TRIGGER_S00_AXI_SLV_REG084_OFFSET
#define COMPATIBILITY_SCALAR_A_ENAB_ADDR 084
#define COMPATIBILITY_SCALAR_A_COUNT SDE_TRIGGER_S00_AXI_SLV_REG087_OFFSET
#define COMPATIBILITY_SCALAR_A_COUNT_ADDR 087

#define COMPATIBILITY_SCALAR_B_THR0 SDE_TRIGGER_S00_AXI_SLV_REG088_OFFSET
#define COMPATIBILITY_SCALAR_B_THR0_ADDR 088
#define COMPATIBILITY_SCALAR_B_THR1 SDE_TRIGGER_S00_AXI_SLV_REG089_OFFSET
#define COMPATIBILITY_SCALAR_B_THR1_ADDR 089
#define COMPATIBILITY_SCALAR_B_THR2 SDE_TRIGGER_S00_AXI_SLV_REG090_OFFSET
#define COMPATIBILITY_SCALAR_B_THR2_ADDR 090
#define COMPATIBILITY_SCALAR_B_ENAB SDE_TRIGGER_S00_AXI_SLV_REG092_OFFSET
#define COMPATIBILITY_SCALAR_B_ENAB_ADDR 092
#define COMPATIBILITY_SCALAR_B_COUNT SDE_TRIGGER_S00_AXI_SLV_REG095_OFFSET
#define COMPATIBILITY_SCALAR_B_COUNT_ADDR 095

#define COMPATIBILITY_SCALAR_C_THR0 SDE_TRIGGER_S00_AXI_SLV_REG096_OFFSET
#define COMPATIBILITY_SCALAR_C_THR0_ADDR 096
#define COMPATIBILITY_SCALAR_C_THR1 SDE_TRIGGER_S00_AXI_SLV_REG097_OFFSET
#define COMPATIBILITY_SCALAR_C_THR1_ADDR 097
#define COMPATIBILITY_SCALAR_C_THR2 SDE_TRIGGER_S00_AXI_SLV_REG098_OFFSET
#define COMPATIBILITY_SCALAR_C_THR2_ADDR 098
#define COMPATIBILITY_SCALAR_C_ENAB SDE_TRIGGER_S00_AXI_SLV_REG100_OFFSET
#define COMPATIBILITY_SCALAR_C_ENAB_ADDR 100
#define COMPATIBILITY_SCALAR_C_COUNT SDE_TRIGGER_S00_AXI_SLV_REG103_OFFSET
#define COMPATIBILITY_SCALAR_C_COUNT_ADDR 103

#define COMPATIBILITY_SHADOW_SHWR_BUF_TRIG_MASK SDE_TRIGGER_S00_AXI_SLV_REG123_OFFSET
#define COMPATIBILITY_SHADOW_SHWR_BUF_TRIG_MASK_ADDR 123
#define COMPATIBILITY_SHADOW_SHWR_BUF_TRIG_ID SDE_TRIGGER_S00_AXI_SLV_REG124_OFFSET
#define COMPATIBILITY_SHADOW_SHWR_BUF_TRIG_ID_ADDR 124
#define COMPATIBILITY_SHADOW_SHWR_BUF_STATUS SDE_TRIGGER_S00_AXI_SLV_REG126_OFFSET
#define COMPATIBILITY_SHADOW_SHWR_BUF_STATUS_ADDR 126

#define COMPATIBILITY_ID_B SDE_TRIGGER_S00_AXI_SLV_REG127_OFFSET
#define COMPATIBILITY_ID_B_ADDR 127

// Normal mode registers.  Note that the global trigger control and the
// buffer handling are done using the normal mode registers as the readout
// operations are necessarily different than in the before 2015 implementation.

// Shower memory status & control registers
// Note that the status register should be read atomicly, which is why
// multiple fields are packed into one register.
#define SHWR_BUF_TRIG_MASK SDE_TRIGGER_S00_AXI_SLV_REG128_OFFSET
#define SHWR_BUF_TRIG_MASK_ADDR 128
#define SHWR_BUF_TRIG_ID SDE_TRIGGER_S00_AXI_SLV_REG129_OFFSET
#define SHWR_BUF_TRIG_ID_ADDR 129
#define SHWR_BUF_CONTROL SDE_TRIGGER_S00_AXI_SLV_REG130_OFFSET
#define SHWR_BUF_CONTROL_ADDR 130
#define SHWR_BUF_STATUS SDE_TRIGGER_S00_AXI_SLV_REG131_OFFSET
#define SHWR_BUF_STATUS_ADDR 131
 #define SHWR_BUF_RNUM_MASK ((1<<SHWR_BUF_NUM_WIDTH)-1)
 #define SHWR_BUF_RNUM_SHIFT 0
 #define SHWR_BUF_WNUM_MASK ((1<<SHWR_BUF_NUM_WIDTH)-1)
 #define SHWR_BUF_WNUM_SHIFT (SHWR_BUF_RNUM_SHIFT+SHWR_BUF_NUM_WIDTH)
 #define SHWR_BUF_FULL_MASK ((1<<SHWR_MEM_NBUF)-1)
 #define SHWR_BUF_FULL_SHIFT (SHWR_BUF_WNUM_SHIFT+SHWR_BUF_NUM_WIDTH)
 #define SHWR_INTR_PEND_MASK 1
 #define SHWR_INTR_PEND_SHIFT (SHWR_BUF_FULL_SHIFT+SHWR_MEM_NBUF)
#define SHWR_BUF_START SDE_TRIGGER_S00_AXI_SLV_REG132_OFFSET
#define SHWR_BUF_START_ADDR 132
#define SHWR_BUF_START0 SDE_TRIGGER_S00_AXI_SLV_REG133_OFFSET
#define SHWR_BUF_START0_ADDR 133
#define SHWR_BUF_START1 SDE_TRIGGER_S00_AXI_SLV_REG134_OFFSET
#define SHWR_BUF_START1_ADDR 134
#define SHWR_BUF_START2 SDE_TRIGGER_S00_AXI_SLV_REG135_OFFSET
#define SHWR_BUF_START2_ADDR 135
#define SHWR_BUF_START3 SDE_TRIGGER_S00_AXI_SLV_REG136_OFFSET
#define SHWR_BUF_START3_ADDR 136

#endif // #ifndef _TRIGGER_DEFS
